apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-worker-14771
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/core-worker-14771
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
